### ISSUE TITLE
ใช้ไปสักพักแล้วเพี้ยน

### ISSUE THREAD

**Issue by asnise** [3tew/rox-auto-fishing#1]
แบบ H แล้วมันกดเองเลยแล้วก็มันจะไม่ทำงานตอนวงเขียวเลย

**Comment by 3tew** [comment]
มันต้อง Alt + Tab ไปที่ตัวแสดงผลอะครับ แล้วกด H
เดี๋ยวว่างแล้วจะทำ Keyboard Listener ครับผม

**Comment by 3tew** [comment]
> แบบ H แล้วมันกดเองเลยแล้วก็มันจะไม่ทำงานตอนวงเขียวเลย

แนะนำว่าให้เอาปุ่มอยู่บนน้ำใว้ครับ หรือ พื้นที่ๆไม่เป็นสีเขียว ไม่งั้นมัน detect เพี้ยน
